### ISSUE TITLE
Automatic game information download: Different games share same info

### ISSUE THREAD

**Issue by brunomueller93** [angstsmurf/spatterlight#24]
Hi there! Love this program a lot! 

I have an issue though. I've imported all of my games into Spatterlight and used the automatic information download function. It worked fine for most games but the games "Zork I" and "Suspended" now share the same information. Spatterlight calls them both "Zork I" and whenever I try to change Suspended's information, it also changes Zork I's info. Those two games are now somehow interlinked.

**Comment by angstsmurf** [comment]
Thanks for reporting this!

Looking at the list [here](https://eblong.com/infocom/#suspended), there are hacked versions of Zork I and Suspended that have the same blank serial number, which is why they get the same IFID ("ZCODE-5-------") and IFDB data.

Spatterlight uses this ID to tell games apart, and it would require a pretty fundamental change to fix this. For now the only solution seems to be to use a different version of Suspended, as that is the one that gest mis-identified.

This isn't really a Spatterlight bug, so I've reported it [here](https://github.com/iftechfoundation/babel-tool/issues/10).

**Comment by brunomueller93** [comment]
Hi, thanks for looking into this! 

But apart from the same ID, couldn't Splatterlight differentiate between games also based on their file paths? Having the same info after the automatic info download is one thing. But I find it worse when it's impossible for me to manually change the information after it has been automatically downloaded. Whenever I try to change Suspended's info, Splatterlight also changes Zork I's info and vice versa. It would be nice if it would be possible to manually change the info anyway. 

But anyway, thanks a lot for looking into this! I really love this project!

**Comment by angstsmurf** [comment]
Yes, the current way is obviously not ideal. But it has been this way since the beginning, and it would be a lot of work to change it now. It is on my list, though. In the meantime, IFID is supposed to be a unique identifier that prevents this sort of thing from happening, so if it is fixed on the Babel side, it will take care of your problem as well.
