### ISSUE TITLE
Preference to open games without adding them to the library

### ISSUE THREAD

**Issue by dfabulich** [angstsmurf/spatterlight#40]
During IFComp, I play a lot of games that I don't intend to use/keep forever. Since I've configured Spatterlight to be the default app for `.gblorb` files, Spatterlight adds a reference to these files in its library when I double-click to open them, even if I intend to play them only once and toss them later.

I wish there were a preference allowing me disable automatically adding games to my library.

**Comment by angstsmurf** [comment]
This is actually a behaviour that I found annoying in iTunes as well, which Spatterlight is obviously modeled on.

The library and its database are central to how Spatterlight works, and it would not be trivial to change. To add a "Open games without adding them to the library" setting I guess you would have to create a way for library entries to be hidden, so that games would be added but not shown in the library window. Then we would have to make sure that they are unhidden when the same game is added in the old standard way.

**Comment by dfabulich** [comment]
Perhaps #42 and/or #45 would be a better way to satisfy my goal for this issue.

**Comment by dfabulich** [comment]
I think this is done in 0.8.9!
