### ISSUE TITLE
Empty column on the library screen

### ISSUE THREAD

**Issue by dfabulich** [angstsmurf/spatterlight#41]
https://github.com/angstsmurf/spatterlight/raw/master/readme_images/library.png

Actual: There's a stray empty column on the left side of the library. When I click on it, it appears to do forward/reverse alphabetical title sort.

Expected: That empty column shouldn't be there. The first column should just be the Title column.

**Comment by dfabulich** [comment]
I've been using Spatterlight for years and I kinda can't believe that I only just noticed this now!

**Comment by angstsmurf** [comment]
This is actually the "Found" column, which shows an exclamation mark in a circle if the game file can't be found, usually because it has been deleted in Finder. If you have games that are not found, they will be sorted on top when this is clicked. I guess it should be added to the contextual menu that lets you select which table headers are visible, so that it becomes possible to hide.

**Comment by dfabulich** [comment]
My intuition is that "Found" status should be represented as a red exclamation icon in the Title (and that there's no need to sort by it).

**Comment by angstsmurf** [comment]
I added the Found column to the header menu, so now it can be hidden.
